import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import * as XLSX from "xlsx";
import {Home,Warehouse,Egg,Wheat,Syringe,ShoppingCart,CreditCard,Wallet,AlertTriangle,BarChart3,Plus,Search,Download,Menu,X,Trash2,Database,RefreshCw,FileText,Users,ArrowDownToLine,ArrowUpFromLine} from "lucide-react";
import "./style.css";

const KEY="ternakpro_v4";
const empty={periode:[],kandang:[],ayam:[],produksi:[],pakan:[],obat:[],penjualan:[],piutang:[],pembayaran:[],biaya:[],kerugian:[]};
const load=()=>{try{return {...empty,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return {...empty}}};
const num=n=>Number(n)||0;
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(num(n));
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID();
const sum=(arr,k)=>arr.reduce((a,x)=>a+num(x[k]),0);
function Card({title,value,icon:Icon,sub}){return <div className="card"><div className="cardtop"><span>{title}</span><Icon size={19}/></div><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
function Modal({title,onClose,children}){return <div className="overlay"><div className="modal"><div className="modalhead"><h3>{title}</h3><button onClick={onClose}><X size={19}/></button></div>{children}</div></div>}
const menu=[["dashboard","Dashboard",Home],["periode","Periode Ternak",Users],["ternak","Ternak & Kandang",Warehouse],["produksi","Produksi Harian",Egg],["stok","Stok Pakan & Obat",Wheat],["penjualan","Penjualan",ShoppingCart],["piutang","Piutang",CreditCard],["biaya","Biaya Operasional",Wallet],["kerugian","Kerugian",AlertTriangle],["laporan","Laporan",BarChart3]];
function App(){
 const [db,setDb]=useState(load),[page,setPage]=useState("dashboard"),[modal,setModal]=useState(false),[modalPage,setModalPage]=useState("dashboard"),[search,setSearch]=useState(""),[mobile,setMobile]=useState(false),[period,setPeriod]=useState("all");
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(db)),[db]);
 const periods=db.periode;
 const activePeriod=period==="all"?null:periods.find(x=>x.id===period);
 const inPeriod=x=>!activePeriod||!x.periodeId||x.periodeId===activePeriod.id;
 const filtered=(k)=>db[k].filter(x=>inPeriod(x)&&JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
 const add=(k,o)=>{setDb(d=>({...d,[k]:[...d[k],{id:uid(),...o}]}));setModal(false)}; const openAdd=p=>{setModalPage(p);setModal(true)};
 const del=(k,id)=>setDb(d=>({...d,[k]:d[k].filter(x=>x.id!==id)}));
 const prod=db.produksi.filter(inPeriod), salesRows=db.penjualan.filter(inPeriod), costsRows=db.biaya.filter(inPeriod), losses=db.kerugian.filter(inPeriod), debtsRows=db.piutang.filter(inPeriod), pays=db.pembayaran.filter(inPeriod);
 const live=prod.length?num(prod[prod.length-1].ayamHidup):sum(db.ayam.filter(inPeriod),"jumlah");
 const eggs=sum(prod,"totButir"),eggkg=sum(prod,"totKg"),sales=sum(salesRows,"total"),costs=sum(costsRows,"total"),loss=sum(losses,"nilai");
 const credit=sum(debtsRows,"total"),paid=sum(pays,"jumlah"),debts=Math.max(0,credit-paid),profit=sales-costs-loss;
 function backup(){download(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),"ternakpro-v4-backup.json")}
 function restore(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setDb({...empty,...JSON.parse(r.result)})}catch{alert("Backup tidak valid.")}};r.readAsText(f)}
 function excel(){const wb=XLSX.utils.book_new();Object.entries(db).forEach(([k,v])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(v.length?v:[{}]),k.slice(0,31)));XLSX.writeFile(wb,"TERNAKPRO-Laporan-v4.xlsx")}
 const current=menu.find(x=>x[0]===page);
 return <div className={"app "+(mobile?"mobileopen":"")}>
  <aside className="sidebar"><div className="brand"><div className="logo">🐔</div><div><strong>TERNAKPRO</strong><small>Manajemen Ayam Petelur</small></div></div><nav>{menu.map(([id,l,I])=><button className={page===id?"active":""} onClick={()=>{setPage(id);setSearch("");setMobile(false)}} key={id}><I size={18}/>{l}</button>)}</nav><div className="sidefoot">V4 • Data tersimpan otomatis<br/>di perangkat ini</div></aside>
  <main><header><button className="menubtn" onClick={()=>setMobile(!mobile)}><Menu/></button><div><h1>{current?.[1]}</h1><span>{new Date().toLocaleDateString("id-ID",{dateStyle:"full"})}</span></div>{page!=="dashboard"&&page!=="laporan"&&<button className="add" onClick={()=>openAdd(page)}><Plus/> Tambah</button>}</header>
   <div className="toolbar"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Semua periode ternak</option>{periods.map(p=><option key={p.id} value={p.id}>{p.nama}</option>)}</select>{page!=="dashboard"&&page!=="laporan"&&<div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari tanggal, nama, nota..."/></div>}</div>
   {page==="periode"&&<PeriodPage db={db} setDb={setDb}/>}
   {page==="dashboard"&&<Dashboard live={live} eggs={eggs} eggkg={eggkg} sales={sales} costs={costs} debts={debts} loss={loss} profit={profit} db={prod} go={setPage}/>} 
   {page==="ternak"&&<Table title="Data Ternak & Kandang" rows={filtered("ayam")} cols={[["periodeId","Periode"],["kandang","Kandang"],["tanggalMasuk","Masuk"],["jumlah","Ekor"],["umur","Umur (mg)"],["ras","Ras"],["harga","Harga/ekor"]]} del={id=>del("ayam",id)} moneyKeys={["harga"]} periodNames={periods}/>} 
   {page==="produksi"&&<Table title="Produksi Harian" rows={filtered("produksi")} cols={[["tanggal","Tanggal"],["ayamHidup","Ayam hidup"],["mati","Mati"],["hilang","Hilang"],["totButir","Total butir"],["totKg","Total kg"],["pakanKg","Pakan kg"],["fcr","FCR"]]} del={id=>del("produksi",id)}/>} 
   {page==="stok"&&<Stock db={db} setDb={setDb} period={period}/>} 
   {page==="penjualan"&&<Table title="Penjualan Telur & Ayam" rows={filtered("penjualan")} cols={[["tanggal","Tanggal"],["nota","Nota"],["pembeli","Pembeli"],["barang","Barang"],["mutu","Mutu"],["qty","Qty"],["satuan","Satuan"],["harga","Harga"],["total","Total"],["status","Status"]]} del={id=>del("penjualan",id)} moneyKeys={["harga","total"]}/>} 
   {page==="piutang"&&<Table title="Piutang Usaha" rows={filtered("piutang")} cols={[["tanggal","Tanggal"],["nota","Nota"],["pelanggan","Pelanggan"],["barang","Barang"],["total","Total"],["jatuhTempo","Jatuh tempo"]]} del={id=>del("piutang",id)} moneyKeys={["total"]} extra={<div className="notice">Sisa piutang <b>{money(debts)}</b> • Pembayaran <b>{money(paid)}</b><span className="right">Transaksi: {debtsRows.length}</span></div>}/>} 
   {page==="pembayaran"&&<Table title="Pembayaran Piutang" rows={filtered("pembayaran")} cols={[["tanggal","Tanggal"],["nota","Invoice"],["pelanggan","Pelanggan"],["jumlah","Jumlah"],["metode","Metode"]]} del={id=>del("pembayaran",id)} moneyKeys={["jumlah"]}/>}
   {page==="biaya"&&<Table title="Biaya Operasional" rows={filtered("biaya")} cols={[["tanggal","Tanggal"],["kategori","Kategori"],["keterangan","Keterangan"],["total","Total"]]} del={id=>del("biaya",id)} moneyKeys={["total"]}/>} 
   {page==="kerugian"&&<Table title="Kerugian" rows={filtered("kerugian")} cols={[["tanggal","Tanggal"],["jenis","Jenis"],["jumlah","Jumlah"],["penyebab","Penyebab"],["nilai","Nilai"]]} del={id=>del("kerugian",id)} moneyKeys={["nilai"]}/>} 
   {page==="laporan"&&<Reports db={db} period={period} sales={sales} costs={costs} loss={loss} debts={debts} profit={profit} excel={excel} backup={backup} restore={restore}/>} 
  </main>
  {modal&&<Form page={modalPage} close={()=>setModal(false)} add={add} db={db} activePeriod={activePeriod}/>} 
 </div>
}
function PeriodPage({db,setDb}){const del=id=>setDb(d=>({...d,periode:d.periode.filter(x=>x.id!==id)}));return <div className="panel tablepanel"><div className="reporthead"><h2>Periode / Siklus Ternak</h2><span>{db.periode.length} periode</span></div><p className="muted">Buat satu periode untuk setiap masuknya flock agar produksi, biaya, penjualan, dan laporan bisa dipisahkan.</p><div className="tablewrap"><table><thead><tr><th>Nama</th><th>Mulai</th><th>Selesai</th><th>Ayam awal</th><th>Status</th><th></th></tr></thead><tbody>{db.periode.map(p=><tr key={p.id}><td>{p.nama}</td><td>{p.tanggalMulai||"-"}</td><td>{p.tanggalSelesai||"-"}</td><td>{p.jumlahAwal||0}</td><td>{p.status||"Aktif"}</td><td><button className="iconbtn" onClick={()=>del(p.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!db.periode.length&&<p className="empty">Belum ada periode. Tekan Tambah untuk membuat siklus pertama.</p>}</div></div>}
function Dashboard({live,eggs,eggkg,sales,costs,debts,loss,profit,db,go}){const max=Math.max(1,...db.slice(-7).map(x=>num(x.totButir)));const fcr=db.length?(sum(db,"pakanKg")/Math.max(0.001,sum(db,"totKg"))).toFixed(2):"-";return <section><div className="cards"><Card title="Ayam Hidup" value={live+" ekor"} icon={Warehouse} sub="Populasi terakhir"/><Card title="Produksi" value={eggs+" butir"} icon={Egg} sub={eggkg.toFixed(1)+" kg total"}/><Card title="Penjualan" value={money(sales)} icon={ShoppingCart} sub="Total tercatat"/><Card title="Piutang" value={money(debts)} icon={CreditCard} sub="Sisa belum dibayar"/></div><div className="cards finance"><Card title="Pendapatan" value={money(sales)} icon={ArrowUpFromLine}/><Card title="Biaya" value={money(costs)} icon={ArrowDownToLine}/><Card title="Kerugian" value={money(loss)} icon={AlertTriangle}/><Card title="Laba Bersih" value={money(profit)} icon={BarChart3} sub={"FCR "+fcr}/></div><div className="grid2"><div className="panel"><h2>Tren Produksi 7 Catatan</h2><div className="bars">{db.slice(-7).map(x=><div className="barwrap" key={x.id}><div className="bar" style={{height:(num(x.totButir)/max*150+5)+"px"}}></div><small>{x.tanggal?.slice(5)}</small></div>)}{!db.length&&<p className="muted">Belum ada produksi.</p>}</div></div><div className="panel"><h2>Ringkasan</h2><div className="summary"><span>Telur</span><b>{eggs.toLocaleString("id-ID")} butir</b><span>Telur kg</span><b>{eggkg.toFixed(1)} kg</b><span>Biaya</span><b>{money(costs)}</b><span>Laba bersih</span><b className={profit>=0?"green":"red"}>{money(profit)}</b></div></div></div><div className="quick"><button onClick={()=>go("produksi")}>🥚 Catat Produksi</button><button onClick={()=>go("penjualan")}>💰 Penjualan</button><button onClick={()=>go("biaya")}>💸 Biaya</button><button onClick={()=>go("piutang")}>💳 Piutang</button></div></section>}
function Table({title,rows,cols,del,moneyKeys=[],extra,periodNames=[]}){const pname=id=>periodNames.find(x=>x.id===id)?.nama||"-";return <div className="panel tablepanel"><div className="reporthead"><h2>{title}</h2><span>{rows.length} data</span></div>{extra}<div className="tablewrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}<th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{cols.map(([k])=><td key={k}>{k==="periodeId"?pname(r[k]):moneyKeys.includes(k)?money(r[k]):(r[k]??"-")}</td>)}<td><button className="iconbtn" onClick={()=>del(r.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">Belum ada data.</p>}</div></div>}
function Stock({db,setDb,period}){const feed=db.pakan.filter(x=>period==="all"||!x.periodeId||x.periodeId===period), meds=db.obat.filter(x=>period==="all"||!x.periodeId||x.periodeId===period);const addFeed=()=>setDb(d=>({...d,pakan:[...d.pakan,{id:uid(),nama:"Layer 1",stokKg:0,hargaKg:0,masukKg:0,terpakaiKg:0,rusakKg:0,periodeId:period==="all"?null:period}]}));const addMed=()=>setDb(d=>({...d,obat:[...d.obat,{id:uid(),nama:"Vitamin",stok:0,satuan:"botol",exp:"",periodeId:period==="all"?null:period}]}));return <div className="grid2"><div className="panel"><div className="reporthead"><h2>🌾 Pakan</h2><button onClick={addFeed}><Plus size={16}/> Tambah</button></div>{feed.map(x=><div className="stockrow" key={x.id}><b>{x.nama}</b><span>{num(x.stokKg)} kg • {money(x.hargaKg)}/kg</span></div>)}{!feed.length&&<p className="empty">Belum ada stok pakan.</p>}</div><div className="panel"><div className="reporthead"><h2>💊 Obat & Vaksin</h2><button onClick={addMed}><Plus size={16}/> Tambah</button></div>{meds.map(x=><div className="stockrow" key={x.id}><b>{x.nama}</b><span>{num(x.stok)} {x.satuan||"unit"} • Exp {x.exp||"-"}</span></div>)}{!meds.length&&<p className="empty">Belum ada obat/vaksin.</p>}</div></div>}
function Reports({db,period,sales,costs,loss,debts,profit,excel,backup,restore}){const p=period==="all"?db.produksi:db.produksi.filter(x=>!x.periodeId||x.periodeId===period);const eggs=sum(p,"totButir"),feed=sum(p,"pakanKg"),kg=sum(p,"totKg"),fcr=kg?feed/kg:0;return <div><div className="reporthead"><h2>Laporan & Backup</h2><div className="reportbuttons"><button onClick={excel}><Download/> Excel</button><button onClick={()=>window.print()}><FileText/> Cetak / PDF</button><button onClick={backup}><Database/> Backup</button><label><RefreshCw/> Restore<input type="file" accept=".json" onChange={restore}/></label></div></div><div className="cards"><Card title="Pendapatan" value={money(sales)} icon={ShoppingCart}/><Card title="Biaya" value={money(costs)} icon={Wallet}/><Card title="Kerugian" value={money(loss)} icon={AlertTriangle}/><Card title="Laba Bersih" value={money(profit)} icon={BarChart3}/></div><div className="grid2"><div className="panel"><h2>Produksi</h2><p>Total telur: <b>{eggs.toLocaleString("id-ID")} butir</b></p><p>Total telur: <b>{kg.toFixed(1)} kg</b></p><p>Total pakan: <b>{feed.toFixed(1)} kg</b></p><p>FCR: <b>{fcr?fcr.toFixed(2):"-"}</b></p></div><div className="panel"><h2>Piutang</h2><p>Sisa piutang: <b>{money(debts)}</b></p><p>Invoice piutang: <b>{db.piutang.length}</b></p><p>Pembayaran: <b>{money(sum(db.pembayaran,"jumlah"))}</b></p></div></div><div className="panel formula"><h2>Rumus otomatis</h2><p><b>Ayam hidup</b> = populasi sebelumnya + masuk − mati − hilang − terjual</p><p><b>Stok pakan</b> = stok awal + masuk − terpakai − rusak − hilang</p><p><b>Sisa piutang</b> = total piutang − seluruh pembayaran</p><p><b>Laba bersih</b> = pendapatan − biaya − kerugian</p><p><b>FCR</b> = pakan terpakai (kg) ÷ telur (kg)</p></div></div>}
function Form({page,close,add,db,activePeriod}){const [f,setF]=useState({tanggal:today(),status:"Lunas",barang:"Telur",satuan:"kg",kategori:"Pakan",jenis:"Ayam mati"});const u=(k,v)=>setF(x=>({...x,[k]:v}));const defs={
 periode:[["nama","Nama periode / siklus"],["tanggalMulai","Tanggal mulai","date"],["tanggalSelesai","Tanggal selesai","date"],["jumlahAwal","Jumlah ayam awal","number"],["catatan","Catatan"]],
 ternak:[["kandang","Kandang"],["tanggal","Tanggal masuk","date"],["jumlah","Jumlah ekor","number"],["umur","Umur saat masuk (minggu)","number"],["ras","Ras / sumber"],["harga","Harga beli / ekor","number"]],
 produksi:[["tanggal","Tanggal","date"],["ayamHidup","Ayam hidup","number"],["mati","Mati hari ini","number"],["hilang","Hilang","number"],["telurBesar","Telur besar (butir)","number"],["telurSedang","Telur sedang (butir)","number"],["telurKecil","Telur kecil (butir)","number"],["telurTetel","Tetel (butir)","number"],["retak","Retak (butir)","number"],["busuk","Busuk (butir)","number"],["totKg","Total telur (kg)","number"],["pakanKg","Pakan terpakai (kg)","number"],["catatan","Catatan"]],
 penjualan:[["tanggal","Tanggal","date"],["nota","Nomor nota"],["pembeli","Nama pembeli"],["barang","Barang"],["mutu","Mutu telur"],["qty","Jumlah","number"],["satuan","Satuan"],["harga","Harga satuan","number"]],
 piutang:[["tanggal","Tanggal","date"],["nota","Nomor nota"],["pelanggan","Nama pelanggan"],["barang","Barang"],["total","Total piutang","number"],["jatuhTempo","Jatuh tempo","date"]],
 pembayaran:[["tanggal","Tanggal","date"],["nota","Nomor invoice"],["pelanggan","Pelanggan"],["jumlah","Jumlah pembayaran","number"],["metode","Metode"]],
 biaya:[["tanggal","Tanggal","date"],["kategori","Kategori"],["keterangan","Keterangan"],["total","Total biaya","number"]],
 kerugian:[["tanggal","Tanggal","date"],["jenis","Jenis kerugian"],["jumlah","Jumlah","number"],["penyebab","Penyebab"],["nilai","Nilai kerugian","number"]]
 }[page]||[];
 const submit=e=>{e.preventDefault();const periodeId=activePeriod?.id||null;
  if(page==="periode")return add("periode",{nama:f.nama,tanggalMulai:f.tanggalMulai,tanggalSelesai:f.tanggalSelesai,jumlahAwal:num(f.jumlahAwal),catatan:f.catatan,status:"Aktif"});
  if(page==="ternak")return add("ayam",{periodeId,kandang:f.kandang,tanggalMasuk:f.tanggal,jumlah:num(f.jumlah),umur:num(f.umur),ras:f.ras,harga:num(f.harga)});
  if(page==="produksi"){const vals=["telurBesar","telurSedang","telurKecil","telurTetel","retak","busuk"].map(k=>num(f[k]));return add("produksi",{periodeId,tanggal:f.tanggal,ayamHidup:num(f.ayamHidup),mati:num(f.mati),hilang:num(f.hilang),telurBesar:vals[0],telurSedang:vals[1],telurKecil:vals[2],telurTetel:vals[3],retak:vals[4],busuk:vals[5],totButir:vals.reduce((a,b)=>a+b,0),totKg:num(f.totKg),pakanKg:num(f.pakanKg),fcr:num(f.totKg)?(num(f.pakanKg)/num(f.totKg)).toFixed(2):"",catatan:f.catatan});}
  if(page==="penjualan"){const total=num(f.qty)*num(f.harga);add("penjualan",{periodeId,tanggal:f.tanggal,nota:f.nota||"TRX-"+Date.now(),pembeli:f.pembeli,barang:f.barang,mutu:f.mutu||"-",qty:num(f.qty),satuan:f.satuan,harga:num(f.harga),total,status:f.status});if(f.status!=="Lunas")add("piutang",{periodeId,tanggal:f.tanggal,nota:f.nota||"TRX-"+Date.now(),pelanggan:f.pembeli,barang:f.barang,total,jatuhTempo:f.jatuhTempo||f.tanggal});return;}
  if(page==="piutang")return add("piutang",{periodeId,tanggal:f.tanggal,nota:f.nota||"PIU-"+Date.now(),pelanggan:f.pelanggan,barang:f.barang,total:num(f.total),jatuhTempo:f.jatuhTempo});
  if(page==="pembayaran")return add("pembayaran",{periodeId,tanggal:f.tanggal,nota:f.nota,pelanggan:f.pelanggan,jumlah:num(f.jumlah),metode:f.metode});
  if(page==="biaya")return add("biaya",{periodeId,tanggal:f.tanggal,kategori:f.kategori,keterangan:f.keterangan,total:num(f.total)});
  if(page==="kerugian")return add("kerugian",{periodeId,tanggal:f.tanggal,jenis:f.jenis,jumlah:num(f.jumlah),penyebab:f.penyebab,nilai:num(f.nilai)});
 };
 return <Modal title="Tambah data" onClose={close}><form onSubmit={submit}>{page==="penjualan"&&<label>Status<select value={f.status} onChange={e=>u("status",e.target.value)}><option>Lunas</option><option>Belum Lunas</option><option>Sebagian</option></select></label>}{defs.map(([k,l,t])=><label key={k}>{l}<input type={t||"text"} value={f[k]??""} onChange={e=>u(k,e.target.value)} required={t==="date"||["jumlah","ayamHidup","qty","harga","total","nilai","pelanggan","pembeli"].includes(k)}/></label>)}<button className="submit">Simpan</button></form></Modal>}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
createRoot(document.getElementById("root")).render(<App/>);
